### ISSUE TITLE
Pre commit hook not working

### ISSUE THREAD

**Issue by yevgenypats** [cloudquery/terraform-aws-cloudquery#14]
Either Im doing something wrong or Im hitting a bug in pre-commit. If I enable the pre-commit checks the CI fails with the following error: https://github.com/cloudquery/terraform-aws-cloudquery/runs/4758161059?check_suite_focus=true#step:4:47

```
│   on main.tf line 175, in module "eventbridge":
│  175:           "hcl" : file("${path.module}/tasks/config.hcl")
│     ├────────────────
│     │ path.module is "."
```

Even though I think everything is correct ^ . Is it possible we hit this issue - https://github.com/antonbabenko/pre-commit-terraform/issues/225 or is it something else ? 

@antonbabenko do you if we hit a bug or doing something wrong ?

**Comment by antonbabenko** [comment]
I can see that it started failing in #9 where `config.hcl` was missing, so `terraform validate` failed correctly.

When I run the same command as CI does but locally on `main` branch now, it works as expected because `config.hcl` is there:
> pre-commit run terraform_validate --color=always --show-diff-on-failure --files $(ls *.tf)

I think you can revert the commented lines and it should work as long as the code is valid.

Issue 225 in pre-commit-terraform is not related to the problem you've experienced here.

You can also ask developers to run `pre-commit install --install-hooks` once to have `pre-commit` run automatically. It will fix the docs and formatting locally before the commit happens.

**Comment by yevgenypats** [comment]
@antonbabenko I see. You are right! sorry - my bad :)

**Comment by antonbabenko** [comment]
No problems! Happy to help in the future, too.
